# Generated by Django 3.1.1 on 2020-09-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200928_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ingredient_text',
        ),
    ]
