# Generated by Django 3.1.1 on 2020-09-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200929_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main_category',
            new_name='Main_categorie',
        ),
    ]
